```{r}
library(tidyverse)
library(dplyr)
library(plotly)
```

```{r}
start = read.csv(("../data/start.csv"), header=FALSE)
colnames(start) <- c("PID","original_number","start")

end = read.csv(("../data/end.csv"), header=FALSE)
colnames(end) <- c("PID","original_number","end")

time = merge(start, end, by=c("PID", "original_number")) %>%
  mutate(time = end-start) %>% 
  select(c("PID","original_number","time"))

time = time %>%
  mutate(type = "process")

time$PID <- NULL

time
```

```{r}
ggplotly(
  ggplot(data=time, aes(x=type, y=time)) +
    geom_boxplot()
)
```

```{r}
time = time %>%
  filter(time < 261) %>%
  mutate(number = row_number())

ggplotly(
ggplot(data=time, aes(x=type, y=time)) +
    geom_boxplot()
)

time = time %>% 
   mutate(cumulative = cumsum(time))

time
```

```{r}
ggplotly(
  ggplot(data=time, aes(x=number, y=time)) +
    geom_line()
  )

ggplotly(
  ggplot(data=time, aes(x=number, y=cumulative)) +
    geom_line()
  )
```

```{r}
thread = read.csv(("../data/logThread.csv"), header=FALSE)
colnames(thread) <- c("original_number", "time")

thread = thread %>%
  mutate(type = "thread")

thread
```

```{r}
ggplotly(
ggplot(data=thread, aes(x=type, y=time)) +
    geom_boxplot()
)
```

```{r}
thread = thread %>%
  filter(time < 21) %>%
  mutate(number = row_number())

thread = thread %>%
  filter(time > 10)

ggplotly(
ggplot(data=thread, aes(x=type, y=time)) +
    geom_boxplot()
)

ggplotly(
  ggplot(data=thread, aes(x=number, y=time)) +
    geom_line()
)
```

```{r}
thread = thread %>% 
   mutate(cumulative = cumsum(time))

thread
```

```{r}
ggplotly(
  ggplot(data=thread, aes(x=number, y=time)) +
    geom_line()
  )

ggplotly(
  ggplot(data=thread, aes(x=number, y=cumulative)) +
    geom_line()
  )
```

```{r}
final = rbind(thread, time)

final
```

```{r}
ggplotly(
ggplot(data=final, aes(x=number, y=time, color = type)) +
  geom_line()
)

ggplotly(
ggplot(data=final, aes(x=cumulative, y=number, color = type)) +
  geom_line() +
  xlab("Tempo (Microsegundos)") +
  ylab("Número de Processos/Threads")
)
```
